# Generated by Django 2.2.12 on 2021-11-25 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, verbose_name='顯示區位')),
                ('name', models.TextField(null=True, verbose_name='產品名稱')),
                ('plu', models.TextField(null=True, verbose_name='POS編碼')),
                ('content', models.TextField(verbose_name='圖片名稱')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=7, verbose_name='價格')),
                ('saleout', models.BooleanField(default=False, null=True, verbose_name='是否售完')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='創建时間')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时間')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活躍')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
        migrations.CreateModel(
            name='NoteB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, verbose_name='顯示區位')),
                ('name', models.TextField(null=True, verbose_name='產品名稱')),
                ('plu', models.TextField(null=True, verbose_name='POS編碼')),
                ('content', models.TextField(verbose_name='圖片名稱')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=7, verbose_name='價格')),
                ('saleout', models.BooleanField(default=False, null=True, verbose_name='是否售完')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='創建时間')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时間')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活躍')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, verbose_name='顯示區位')),
                ('name', models.TextField(null=True, verbose_name='產品名稱')),
                ('plu', models.TextField(null=True, verbose_name='POS編碼')),
                ('content', models.TextField(verbose_name='圖片名稱')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=7, verbose_name='價格')),
                ('saleout', models.BooleanField(default=False, null=True, verbose_name='是否售完')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='創建时間')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时間')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活躍')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
    ]
