# Generated by Django 2.2.12 on 2021-11-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.TextField(null=True, verbose_name='店名')),
                ('store_tel', models.TextField(null=True, verbose_name='電話')),
                ('store_pre1', models.TextField(null=True, verbose_name='電話')),
            ],
        ),
    ]
